[package]
name = "spl-discriminator"
version = "0.4.1"
description = "SPL discriminator library for Solana programs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/hamkj7hpo/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
solana-program = "2.3.0"
bytemuck = { version = "1.18.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]
